### PR TITLE
Test CardOwnership

### PR DESCRIPTION
**Pull request by harrischristiansen**
Add tests for createCard, ownerOf, and balanceOf

https://github.com/CryptoCardsETH/cryptocards/issues/3

### CODE REVIEW

**Review by Shonas301 — APPROVED** [review]
Approved:
createCard function
New Migration (#2)
TestCardOwnership

**Comment by nickysemenza** [comment]
how about some travis integration? 😄 
(If you don't want to mess with it I can do it if you tell me how you run the tests)

**Comment by harrischristiansen** [comment]
@nickysemenza Travis integration would be great. However, testing requires a full ethereum network running on the machine. I'm not sure automated tests will be possible once we deploy to ethereum's test network.

To test currently, truffle points to my local ethereum node (127.0.0.1), and I do the following:
```
truffle compile
truffle test
```

**Comment by nickysemenza** [comment]
@harrischristiansen atheneums? 

Totally forgot it needs a working node. what's the quickest time that a geth node can be spun up to a state in which tests will pass? CircleCI supports docker for there tests, so I was thinking of making a full-stack docker-compose image that integration tests can run inside? But if it takes 5 minutes to sync the node then that wouldn't be super great...

**Pull request merged**
